- name: Coursework
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Create coursework
      docker_container:
        name: coursework
        image: znak07/courseworkapp1
        pull: true
        state: started
        ports:
          - "80:80"